### 여정 순서 잘못된 버전 (중복된 버전)
POST http://localhost:8080/api/member/1/trip-itineraries/1
Content-Type: application/json

[
  {
    "type": "MOVEMENT",
    "item": "비행기",
    "startDate": "2023-10-22T12:24:10",
    "endDate": "2023-10-22T22:00:10",
    "order": 1,
    "departurePlace": "인천 공항",
    "arrivalPlace": "도쿄 공항"
  },
  {
    "type": "STAY",
    "item": "도쿄 디즈니월드",
    "startDate": "2023-10-26T12:00:10",
    "endDate": "2023-10-26T20:03:10",
    "order": 2
  },
  {
    "type": "LODGEMENT",
    "item": "신주쿠 워싱턴 호텔",
    "startDate": "2023-10-22T15:00:10",
    "endDate": "2023-10-25T10:00:10",
    "order": 2
  }
]

