### 여정 출발 날짜가 도착 날짜보다 늦을때
POST http://localhost:8080/api/member/1/trip-itineraries/1
Content-Type: application/json

[
  {
    "type": "MOVEMENT",
    "item": "비행기",
    "startDate": "2023-10-29T12:24:10",
    "endDate": "2023-10-22T22:00:10",
    "order": 1,
    "departurePlace": "인천 공항",
    "arrivalPlace": "도쿄 공항"
  }
]

