POST http://localhost:8080/api/member/1/trip-itineraries/3
Content-Type: application/json

[
  {
    "type": "MOVEMENT",
    "item": "버스",
    "startDate": "2023-10-25T17:03:10",
    "endDate": "2023-10-25T17:03:10",
    "order": 4,
    "departurePlace": "도쿄 타워",
    "arrivalPlace": "도쿄 디즈니랜드"
  },
  {
    "type": "STAY",
    "item": "도쿄 타워",
    "startDate": "2023-10-25T17:03:10",
    "endDate": "2023-10-25T17:03:10",
    "order": 3
  },
  {
    "type": "LODGEMENT",
    "item": "도쿄 온천있는 호텔",
    "startDate": "2023-10-25T17:03:10",
    "endDate": "2023-10-25T17:03:10",
    "order": 5
  }
]

