POST http://localhost:8080/itineraries/5
Content-Type: application/json

[
  {
    "type" : "MOVEMENT",
    "item" : "비행기",
    "startDate" : "2023-10-25T17:03:10",
    "endDate" : "2023-10-25T17:03:10",
    "order" : 1,
    "departurePlace" : "인천 공항",
    "arrivalPlace" : "도쿄 공항"
  },
  {
    "type" : "STAY",
    "item" : "디즈니월드",
    "startDate" : "2023-10-25T17:03:10",
    "endDate" : "2023-10-25T17:03:10",
    "order" : 2
  },
  {
    "type" : "LODGEMENT",
    "item" : "도쿄 호텔",
    "startDate" : "2023-10-25T17:03:10",
    "endDate" : "2023-10-25T17:03:10",
    "order" : 3
  }
]

