PUT http://localhost:8080/itineraries/1
Content-Type: application/json

[
  {
    "itineraryId": 3,
    "type": "LODGEMENT",
    "item": "도쿄 호텔2",
    "startDate": "2023-12-12T17:03:10",
    "endDate": "2023-12-12T17:03:10",
    "order": 2
  }
]

